DROP DATABASE GTG;
CREATE DATABASE GTG;
USE GTG;

CREATE TABLE Members (
 MemberID INT(10) NOT NULL
 ,FirstName VARCHAR(30) NOT NULL
 ,LastName VARCHAR(30) NOT NULL
 ,JoinDate DATE NOT NULL
 ,Email VARCHAR(100) NOT NULL
 ,Address VARCHAR(100) NOT NULL
 ,PhoneNum INT(10) NOT NULL
 ,PRIMARY KEY (MemberID)
);

CREATE TABLE Orders (
 OrderID CHAR(6) NOT NULL
 ,MemberID INT(10) NOT NULL
 ,OrderTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
 ,OrderStatus ENUM('PAID', 'PENDING', 'FAIL') DEFAULT 'PENDING' NOT NULL
 ,Info VARCHAR(300)
 ,PRIMARY KEY (OrderID)
 ,FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
);

CREATE TABLE Products (
 ProductID CHAR(6) NOT NULL
 ,ProductName VARCHAR(100) NOT NULL
 ,Category VARCHAR(30) NOT NULL
 ,Unit VARCHAR(10) NOT NULL
 ,Price INT(10) NOT NULL
 ,Stock INT(10) NOT NULL
 ,ExpiryDate DATE NOT NULL
 ,PRIMARY KEY (ProductID)
);

CREATE TABLE OrderItems (
 OrderID CHAR(6) NOT NULL
 ,ProductID CHAR(6) NOT NULL
 ,Quantity INT(10) NOT NULL
 ,PRIMARY KEY (OrderID, ProductID)
 ,FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
 ,FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);